import {AppProvider} from "@/components/AppContext";
import Header from "@/components/layout/Header";
import { Roboto } from 'next/font/google'
import './globals.css'
import {Toaster} from "react-hot-toast";
import Head from "next/head";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Food-Ordering',
  description: 'Generated by Aman Chauhan',
  icons: {
    icon: "/favicon.ico",  // Ensure you have this file in the 'public' folder
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <Head>
        <title>Food Ordering</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
              &copy; 2025 All rights reserved
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
